# Site settings
title: Andrey Atapin
email: me@andreyatapin.com
description: Climbing on the mountain of software development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreyatapin.com" # the base hostname & protocol for your site
twitter_username: a_atapin
github_username:  atapin

# Build settings
markdown: kramdown
